const PostActionTypes = {
  CREATE_POST_START: "CREATE_POST_START",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAIL: "CREATE_POST_FAIL",
  FETCH_POST_START: "FETCH_POST_START",
  FETCH_POST_SUCCESS: "FETCH_POST_SUCCESS",
  FETCH_POST_FAIL: "FETCH_POST_FAIL",
  PHOTO_PATH: "PHOTO_PATH",
  RESET_POST: "RESET_POST",
  PERSIST_USER_POST: "PERSIST_USER_POST",
};

export { PostActionTypes };
