const PostActionTypes = {
  CREATE_POST_START: "CREATE_POST_START",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAIL: "CREATE_POST_FAIL",
  CREATE_PHOTO_START: "CREATE_PHOTO_START",
  CREATE_PHOTO_SUCCESS: "CREATE_PHOTO_SUCCESS",
  CREATE_PHOTO_FAIL: "CREATE_PHOTO_FAIL",
  FETCH_POST_START: "FETCH_POST_START",
  FETCH_POST_SUCCESS: "FETCH_POST_SUCCESS",
  FETCH_POST_FAIL: "FETCH_POST_FAIL",
  PHOTO_PATH: "PHOTO_PATH",
  RESET_POST: "RESET_POST"
};

export { PostActionTypes };
