const friendTypes = {
  SEND_FRIEND_REQUEST_START: "SEND_FRIEND_REQUEST_START",
  SEND_FRIEND_REQUEST_SUCCESS: "SEND_FRIEND_REQUEST_SUCCESS",
  SEND_FRIEND_REQUEST_FAIL: "SEND_FRIEND_REQUEST_FAIL",
};

export { friendTypes };
