const friendTypes = {
  SEND_FRIEND_REQUEST_START: "SEND_FRIEND_REQUEST_START",
  SEND_FRIEND_REQUEST_SUCCESS: "SEND_FRIEND_REQUEST_SUCCESS",
  SEND_FRIEND_REQUEST_FAIL: "SEND_FRIEND_REQUEST_FAIL",
  FIND_REQUEST_RECEIVED_START: "FIND_REQUEST_RECEIVED_START",
  FIND_REQUEST_RECEIVED_SUCCESS: "FIND_REQUEST_RECEIVED_SUCCESS",
  FIND_REQUEST_RECEIVED_FAIL: "FIND_REQUEST_RECEIVED_FAIL",
  ACCEPT_REQUEST_RECEIVED_START: "ACCEPT_REQUEST_RECEIVED_START",
  ACCEPT_REQUEST_RECEIVED_SUCCESS: "ACCEPT_REQUEST_RECEIVED_SUCCESS",
  ACCEPT_REQUEST_RECEIVED_FAIL: "ACCEPT_REQUEST_RECEIVED_FAIL",
};

export { friendTypes };
