const RandomUserTypes = {
  GET_RANDOM_USER_START: "GET_RANDOM_USER_START",
  GET_RANDOM_USER_SUCCESS: "GET_RANDOM_USER_SUCCESS",
  GET_RANDOM_USER_FAIL: "GET_RANDOM_USER_FAIL",
  GET_RANDOM_USER_START2: "GET_RANDOM_USER_START2",
  GET_RANDOM_USER_SUCCESS2: "GET_RANDOM_USER_SUCCESS2",
  GET_RANDOM_USER_FAIL2: "GET_RANDOM_USER_FAIL2",
  GET_RANDOM_USER_START3: "GET_RANDOM_USER_START3",
  GET_RANDOM_USER_SUCCESS3: "GET_RANDOM_USER_SUCCESS3",
  GET_RANDOM_USER_FAIL3: "GET_RANDOM_USER_FAIL3",
};

export { RandomUserTypes };
