const ModalTypes = {
  SHOW_MODAL: "SHOW_MODAL",
  SHOW_CREATE_POST: "SHOW_CREATE_POST",
  SHOW_USER_PHOTOS: "SHOW_USER_PHOTOS",
  SHOW_SIGN_UP: "SHOW_SIGN_UP",
  CLOSE_MODAL: "CLOSE_MODAL",
};

export { ModalTypes };
