const userActionTypes = {
  CREATE_USER_PROFILE_START: "CREATE_USER_PROFILE_START",
  CREATE_USER_PROFILE_SUCCESS: "CREATE_USER_PROFILE_SUCCESS",
  CREATE_USER_PROFILE_FAIL: "CREATE_USER_PROFILE_FAIL",
  GET_ALL_USERS_START: "GET_ALL_USERS_START",
  GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
  GET_ALL_USERS_FAIL: "GET_ALL_USERS_FAIL",
  CHANGE_USER_COVER_START: "CHANGE_USER_COVER_START",
  CHANGE_USER_COVER_SUCCESS: "CHANGE_USER_COVER_SUCCESS",
  CHANGE_USER_COVER_FAIL: "CHANGE_USER_COVER_FAIL",
  // Non Network Actions
  CLEAR_USER_PROFILE_PATH: "CLEAR_USER_PROFILE_PATH",
  GET_USER_PROFILE_PATH: "GET_USER_PROFILE_PATH",
  GET_COVER_PATH: "GET_COVER_PATH",
  CLEAR_COVER_PATH: "CLEAR_COVER_PATH",
  CHANGE_USER_COVER: "CHANGE_USER_COVER",
  CLEAR_PROFILE_CREATED: "CLEAR_PROFILE_CREATED"
};

export { userActionTypes };
