const userActionTypes = {
  GET_USER_PROFILE_PATH: "GET_USER_PROFILE_PATH",
  CLEAR_USER_PROFILE_PATH: "CLEAR_USER_PROFILE_PATH",
  CREATE_USER_PROFILE_START: "CREATE_USER_PROFILE_START",
  CREATE_USER_PROFILE_SUCCESS: "CREATE_USER_PROFILE_SUCCESS",
  CREATE_USER_PROFILE_FAIL: "CREATE_USER_PROFILE_FAIL",
  CHANGE_USER_COVER_START: "CHANGE_USER_COVER_START",
  CHANGE_USER_COVER_SUCCESS: "CHANGE_USER_COVER_SUCCESS",
  CHANGE_USER_COVER_FAIL: "CHANGE_USER_COVER_FAIL",
  GET_COVER_PATH: "GET_COVER_PATH",
  CLEAR_COVER_PATH: "CLEAR_COVER_PATH",
  CHANGE_USER_COVER: "CHANGE_USER_COVER",
};

export { userActionTypes };
