const userActionTypes = {
  GET_USER_PROFILE_PATH: "GET_USER_PROFILE_PATH",
  CLEAR_USER_PROFILE_PATH: "CLEAR_USER_PROFILE_PATH",
  CREATE_USER_PROFILE_START: "CREATE_USER_PROFILE_START",
  CREATE_USER_PROFILE_SUCCESS: "CREATE_USER_PROFILE_SUCCESS",
  CREATE_USER_PROFILE_FAIL: "CREATE_USER_PROFILE_FAIL",
};

export { userActionTypes };
